//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathTweakMod.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathTweakMod.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CastCapeOfWaspsBuff	0b7073c6970a48ffa6dd4c84eb0b1a0c	Kingmaker.Controllers.Brain.Blueprints.BlueprintAiCastSpell
        ///CastDivinePowerFirst	15110917f4494f36acd90ef299fc1026	Kingmaker.Controllers.Brain.Blueprints.BlueprintAiCastSpell
        ///CastSummonWorm	5d73d10132a24ac4b239db3772f5a991	Kingmaker.Controllers.Brain.Blueprints.BlueprintAiCastSpell
        ///CastDisplacementBuff	9dfe17f5a22a44b4aea88e3d95ef272b	Kingmaker.Controllers.Brain.Blueprints.BlueprintAiCastSpell
        ///CastPrayerSecond	0bd35a8100c947db923708f41ec93f01	Kingmaker [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string blueprints {
            get {
                return ResourceManager.GetString("blueprints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 413727c56f7e01d488a473cb95044bde
        ///d48e03729a253814ebb26d21b4e6a0b3
        ///9d213d132b36e554594a362669be2dbe
        ///c41015dbcf456b942b472d626d9b26b0
        ///99ca1864c5ef0404e9b59e70042b6924
        ///5e1c230df5bb6e2469f3c2960901078e
        ///67c085077a5988445984e05d330c7798
        ///a207eff7953731b44acf1a3fa4354c2d
        ///3eb6ad60c8b9fe34fafa32e1f429ff5b
        ///f9df16ffd0c8cec4d99a0ae6f025a3f8
        ///918939943bf32ba4a95470ea696c2ba5
        ///8e43d402ca1a2ad44ac9d2c9fe99f32c
        ///54cf380dee486ff42b803174d1b9da1b
        ///e7aa96d15a45238438ae4cfb476f6bb9
        ///57381165c3f4b4740a872e54f62c3a14
        ///8a6986e17799d7d4b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BrainCloneWhitelist {
            get {
                return ResourceManager.GetString("BrainCloneWhitelist", resourceCulture);
            }
        }
    }
}
